### ISSUE TITLE
后处理方式与原来的 yolov8 不相同

### ISSUE THREAD

**Issue by SunAriesCN** [cqu20160901/yolov8_rknn_Cplusplus#3]
[这行](https://github.com/cqu20160901/yolov8_rknn_Cplusplus/blob/main/examples/rknn_yolov8_demo_open/src/postprocess.cc#L135)代码里面的 cls_val 本来不是要找最大吗？这里直接 sigmoid 输出，大佬是改过 YoloV8 逻辑吗？

```
        for (int h = 0; h < mapSize[index][0]; h++)
        {
            for (int w = 0; w < mapSize[index][1]; w++)
            {
                gridIndex += 2;

                for (int cl = 0; cl < class_num; cl++)
                {
                    cls_val = sigmoid(DeQnt2F32(cls[cl * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w], quant_zp_cls, quant_scale_cls));

                    if (cls_val > objectThresh)
                    {
                        xmin = (meshgrid[gridIndex + 0] - DeQnt2F32(reg[0 * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w], quant_zp_reg, quant_scale_reg)) * strides[index];
                        ymin = (meshgrid[gridIndex + 1] - DeQnt2F32(reg[1 * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w], quant_zp_reg, quant_scale_reg)) * strides[index];
                        xmax = (meshgrid[gridIndex + 0] + DeQnt2F32(reg[2 * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w], quant_zp_reg, quant_scale_reg)) * strides[index];
                        ymax = (meshgrid[gridIndex + 1] + DeQnt2F32(reg[3 * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w], quant_zp_reg, quant_scale_reg)) * strides[index];

                        xmin = xmin > 0 ? xmin : 0;
                        ymin = ymin > 0 ? ymin : 0;
                        xmax = xmax < input_w ? xmax : input_w;
                        ymax = ymax < input_h ? ymax : input_h;

                        if (xmin >= 0 && ymin >= 0 && xmax <= input_w && ymax <= input_h)
                        {
                            temp.xmin = xmin / input_w;
                            temp.ymin = ymin / input_h;
                            temp.xmax = xmax / input_w;
                            temp.ymax = ymax / input_h;
                            temp.classId = cl;
                            temp.score = cls_val;
                            detectRects.push_back(temp);
                        }
                    }
                }
            }
```

**Comment by cqu20160901** [comment]
yolov8的官方代码就是这样写的，可以再看看官方的代码

**Comment by SunAriesCN** [comment]
Yolov8 的[官方](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-CPP-Inference/inference.cpp#L61) 是 ultralytics/ultralytics 吗？方便把 link 贴一下吗？

**Comment by cqu20160901** [comment]
刚有看了一下代码，确实是需要取最大值。但如果NMS的过程是不分类别的进行，取不取最大值都不影响最终的结果。

**Comment by cqu20160901** [comment]
不取最大值出来多个目标，在NMS的时候不分类别的NMS也只会保留一个结果。还是建议按照原始的进行处理

**Comment by SunAriesCN** [comment]
> 刚有看了一下代码，确实是需要取最大值。但如果NMS的过程是不分类别的进行，取不取最大值都不影响最终的结果。

嗯，但 NMS 是 O(N^2) 这可能会影响后处理的计算效率.....

**Comment by cqu20160901** [comment]
> > 刚有看了一下代码，确实是需要取最大值。但如果NMS的过程是不分类别的进行，取不取最大值都不影响最终的结果。
> 
> 嗯，但 NMS 是 O(N^2) 这可能会影响后处理的计算效率.....

这个效率到底是取最大值开销大还是NMS开销大，不好说。对特征图上的每个点的类别都进行取最大值的开销，不见得就比放入到NMS中的开销小。可以测试一下参加nms框的个数，测试了一下本示例中的提供测试图像，参加nms的只有十个框。
![image](https://github.com/cqu20160901/yolov8_rknn_Cplusplus/assets/22290931/570836b1-0d01-4080-8273-72864beaf827)

**Comment by cqu20160901** [comment]
感谢提醒，代码已更新。
![image](https://github.com/cqu20160901/yolov8_rknn_Cplusplus/assets/22290931/3f574d0a-c35c-4d0d-8c11-cde084b8bffd)

**Comment by cqu20160901** [comment]
做了一个小测试，取最大值和不取最大，参加nms的框的数量都不是很多，本示例中取不取最大值参加nms的框都是10个。
![image](https://github.com/cqu20160901/yolov8_rknn_Cplusplus/assets/22290931/91e20b9c-841b-4050-a161-70bfeebac749)

**Comment by SunAriesCN** [comment]
> 做了一个小测试，取最大值和不取最大，参加nms的框的数量都不是很多，本示例中取不取最大值参加nms的框都是10个。 ![image](https://user-images.githubusercontent.com/22290931/253482733-91e20b9c-841b-4050-a161-70bfeebac749.png)

rk3588 还是 3566？
